# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: soi-cloudops-utilities
    type: github
    endpoint: WoolworthsSOI
    name: WoolworthsSOI/soi-cloudops-utilities
    
    
trigger:
    branches:
      include:
      - master
      - feature/*
    paths:
      include:
       - tools/gcp/*
       - tools/common/ci/gcpquotaexport*
      


pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true  # if true, run `execute git clean -ffdx && git reset --hard HEAD` before fetching
  
# Copy files
# Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
- task: CopyFiles@2
  inputs:
    contents: |
      **tools/gcp/**
      **tools/ci/gcpquotaexport/**
      !.emptydir/**/*
      !tools/common/ci/**
    cleanTargetFolder: true # Optional
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'GcpQuotaExport' 
    publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
    #fileCopyOptions: #Optional   
   
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    ls
    dir
    cd
  displayName: 'Run a multi-line script'



